name = "social-media-lab"
client_id = "{{ SHOPIFY_API_KEY }}"
application_url = "https://socialmedialab-production.up.railway.app"
embedded = true

[access_scopes]
scopes = "read_files,write_files,read_products"

[auth]
redirect_urls = [
  "https://socialmedialab-production.up.railway.app/auth/callback",
  "https://socialmedialab-production.up.railway.app/auth/shopify/callback",
  "https://socialmedialab-production.up.railway.app/shopify/auth/callback"
]

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
